### ISSUE TITLE
Textures acting weird

### ISSUE THREAD

**Issue by dum-lab** [SnowyMouse/chimera#119]
Hello there!

I am facing this issue using chimera, the textures start to flicker or weirdly behave in most maps, official and custom.

I've attached a video showing what I say.

Im using the lastest chimera release with no changes on it.

Thanks beforehand

https://github.com/SnowyMouse/chimera/assets/129293598/bd3cfc9f-a433-49b2-b2bb-f24dc48c2032

**Comment by Aerocatia** [comment]
Does this still happen with DXVK or dgVoodoo?

**Comment by MrChromed** [comment]
I remember having a similar behaviour back when I used to disable Vsync and let the GPU (AMD Radeon RX 570) have unlimited FPS. My way to "fix" it was simply enabling Vsync once again and the issues dissapeared. Now that I have a FreeSync monitor, I no longer need to enable Vsync and the game runs just fine, no flickering.

**Comment by Aerocatia** [comment]
I should mention that I don't use vsync but I limit the game to 300 FPS. That might help too.

**Comment by dum-lab** [comment]
> What gpu are you utilizing?
Im using a gtx 1650 mobile

> Does this still happen with DXVK or dgVoodoo?

I have not used DXVK, with dgvoodoo the issue didnt happen but I got terrible, terrible performance



> I remember having a similar behaviour back when I used to disable Vsync and let the GPU (AMD Radeon RX 570) have unlimited FPS. My way to "fix" it was simply enabling Vsync once again and the issues dissapeared. Now that I have a FreeSync monitor, I no longer need to enable Vsync and the game runs just fine, no flickering.

In a first moment I thought this solved my problem, but as soon as I tried some other maps the flickering started again with VSYNC on

**Comment by PseudoProxen** [comment]
>Im using a gtx 1650 mobile

Yeah, this one will be interesting to troubleshoot. Since just looking up this particular chipset, interesting enough; has the same issues in other games. 

What I would double check is turn off any overlays/filters, if an external monitor is being used try just only the laptop screen, & make sure the driver is updated. A slew of others we can try to, but also would like to know what you have done so far.

dgVoodoo2 as of late has been kind of troublesome with its performance as well causing crashes within. This can be due to NVidia driver updates conflicting with dgVoodoo2 current state. But as well looking into your particular chipset it also has some known issues with optimizing VRAM.

**Comment by PseudoProxen** [comment]
Also just looking at this video on an actual desktop, def dealing with issues rendering triangles aka artifacts. So this could be a hardware issue on top of it with GPU overheating or be stressed out. I also check the status on that to be safe.

**Comment by dum-lab** [comment]
> Also just looking at this video on an actual desktop, def dealing with issues rendering triangles aka artifacts. So this could be a hardware issue on top of it with GPU overheating or be stressed out. I also check the status on that to be safe.

Hey, your comments made me realise that my gpu wasnt stressed at all, and that was the problem actually, thing was using the embedded vega graphics instead of the 1650, had to configure display options to force the game to run on the 1650 instead of the integrated graphics! Thanks!
