### ISSUE TITLE
"chimera_load_ui_map" crashes the game.

### ISSUE THREAD

**Issue by Vaporeon** [SnowyMouse/chimera#54]
Some recent change has broken this feature.

**Comment by SnowyMouse** [comment]
Curiously, this seems to have been broken ever since the camera shake fix was implemented. Disabling the fix causes it to not crash the game anymore.

**Comment by SnowyMouse** [comment]
Fixed. It seems there was a missing `ret` instruction, so it just kept going and executing who-knows-what.

For whatever reason, this wasn't a problem until the camera shake fix was implemented, maybe because the function placed in the DLL after it executed and returned without managing to crash the game.

Anyway, fixed.
