### ISSUE TITLE
Add build instruction

### ISSUE THREAD

**Issue by marcospampi** [SnowyMouse/chimera#56]
I feel it is a nightmare, not sarcastic since halloween just happend, to build chimera.
I did once, with great pain, now it doesn't compile.

**Comment by VoidsShadow** [comment]
According to CMakeLists, Chimera requires certain software to build.
* CMake 3.12.4 or newer
* C++17 (C++ Standard 2017) (depends on your preferred compiler
* Git (optional)

### All of which can be downloaded via CygWin:
#### CMake stuff
* CMake (3.12.4 or newer) 
* Ninja Generator
* Python 3.7 or newer

#### Miscellaneous
* Git for versioning changes to source code

#### Compilers
* GCC-Core (vanilla, cygwin32, or mingw64-x86_64 flavored)
* GCC-G++ (vanilla, cygwin32, or mingw64-x86_64 flavored)

### Compiling
You must use forward-slashes or double-back-slashes in the Cygwin Terminal.
1. Start the Cygwin Terminal
2. Enter `cd "<path-to-Chimera's-top-folder>/out/build"`
3. Enter the CMake Configuration command. This would be something like `cmake -S I:/_git/chimera -B I:/_git/chimera/out/build -G Ninja`. -S==Source Directory; -B==Build Directory; -G==Generator;
4. Now enter `ninja` to use the CMake files to build the project.

If you get an error like `ninja: error: '../../src/chimera/localization/language/*', needed by 'localization_strings.hpp', missing and no known rule to make it`, then you're stuck at the same point I am!

**Comment by marcospampi** [comment]
Boi you're all wrong using cygwin at first, use mingw or clang, or get archlinux ( devs use it, I use debian ).
Fact is that you do not know how to build, 'cos there's written nowhere, and there are some issues too that need to be solved, such as curl and zstd firing linking errors, they may need to be built with chimera or removed completely.

**Comment by JerryBrick** [comment]
Woah, I didn't read this before, sorry! 

I was mainly using Arch Linux to build Chimera / Invader, I guess that's the easiest way to do it. If you are on Windows you can simply set up Arch over WSL (this is how i do it).

I was recently working with pR0Ps to configure Github Actions to build Chimera and Invader, since Github Actions runs on Ubuntu we had to rebuild all the libraries in order to build Invader and eventually, Chimera. You can't use the Chimera repository libraries because those libraries were built in Arch (that's the reason you get those ugly errors at link time), you have to rebuild them using the same compiler that you are using to build Chimera, this because (somehow) it isn't the same compiler.

**Comment by marcospampi** [comment]
I catch that, but then it may be better to add those dependencies as submodules.

**Comment by JerryBrick** [comment]
Yes! I'm doing that using CMake's ExternalProject module, if Kava thinks this is a good idea, maybe I'll do a pull request later.

**Comment by marcospampi** [comment]
I do think that's a mandatory solution.

**Comment by JerryBrick** [comment]
Me too, but Kava is the one to decide :p

**Comment by pR0Ps** [comment]
As @JerryBrick mentioned, I was working with them on getting a GitHub action set up to build this project (GitHub actions use Ubuntu). I kinda burnt out on it after fighting with obscure (to me) cmake variables, compiler errors, and library issues.

In order to compile, it needs `libinvader.a`. This is [included in the repo](https://github.com/SnowyMouse/chimera/blob/master/ext/invader/lib/libinvader.a) but if you use a different `gcc` version to compile the project than the one that library was built with, it won't work. At that point I switched gears and started working on a GitHub action to build invader so I could re-use it as part of this build process.

I have it mostly working, but there are still some issues with it. See https://github.com/SnowyMouse/invader/pull/183 . Since it only has issues with the qt binary (I think), the `libinvader.a` that it produces *should* work for building Chimera.

On the other hand, @JerryBrick's "ExternalProject" suggestion also sounds good.

I was pushing to get GitHub Actions working for this project for a few reasons:
 - No matter what system you're developing on, you can push to your local fork of the project and have GitHub do the build for you with no local setup. This is a super slow write-compile-test cycle, but at least it's possible.
 - If you have Docker, you can use something like [act](https://github.com/nektos/act) to run the build locally in a container and not have to worry about cluttering up your system.
 - It can be configured to run on every PR and report any issues, giving more information to the PR reviewer(s).
 - For tagged commits it can automatically create releases, making it easier for users to find the latest builds and update, as well as easier for devs to release an update.

**Comment by marcospampi** [comment]
Yes, I do have the same issue with invader-qt-editor, both on ubuntu 20.04 and debian sid, and I do meet version requirement...
Anyway, you should build invader right away if you disable qt-editor.

**Comment by SnowyMouse** [comment]
Chimera is no longer linked against Invader
